{% set name = "hwatch" %}
{% set version = "0.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/blacknon/hwatch/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0026bf677dd5b6a0c0160e537c6638902917e26aec2265bd0144a6e0f6d78e56

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - hwatch --help

about:
  home: https://github.com/blacknon/hwatch
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern alternative to the watch command
  dev_url: https://github.com/blacknon/hwatch

extra:
  recipe-maintainers:
    - danielnachun
