{% set name = "hwatch" %}
{% set version = "0.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/blacknon/hwatch/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c6d60e837a9f94685581d815265a60a16331c0a3cb2d6fc5abfe1c97963160e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - hwatch --help

about:
  home: https://github.com/blacknon/hwatch
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern alternative to the watch command
  dev_url: https://github.com/blacknon/hwatch

extra:
  recipe-maintainers:
    - danielnachun
