context:
  version: 0.3.18

package:
  name: hwatch
  version: ${{ version }}

source:
  url: https://github.com/blacknon/hwatch/archive/refs/tags/${{ version }}.tar.gz
  sha256: 88c2f172fbf0103aaebd804b6e3bb50f3c847363a300e8104eb83c4c332c0986

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - hwatch --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern alternative to the watch command
  homepage: https://github.com/blacknon/hwatch
  repository: https://github.com/blacknon/hwatch

extra:
  recipe-maintainers:
    - danielnachun
