schema_version: 1

context:
  version: "0.4.1"

package:
  name: hwatch
  version: ${{ version }}

source:
  url: https://github.com/blacknon/hwatch/archive/refs/tags/${{ version }}.tar.gz
  sha256: d2d7ade81e31ae6584ccf0f65bea7fe1a6dc5c79b9d149c2f3b00cd71650ac2e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - hwatch --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern alternative to the watch command
  homepage: https://github.com/blacknon/hwatch
  repository: https://github.com/blacknon/hwatch

extra:
  recipe-maintainers:
    - danielnachun
