context:
  version: 0.3.18

package:
  name: hwatch
  version: ${{ version }}

source:
  url: https://github.com/blacknon/hwatch/archive/${{ version }}.tar.gz
  sha256: db1681c634a39dd6c930441d8bdaa7d875ffc87e9cf7753c6f4bb0a46ff062b0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - hwatch --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern alternative to the watch command
  homepage: https://github.com/blacknon/hwatch
  repository: https://github.com/blacknon/hwatch

extra:
  recipe-maintainers:
    - danielnachun
