schema_version: 1

context:
  version: "0.3.20"

package:
  name: hwatch
  version: ${{ version }}

source:
  url: https://github.com/blacknon/hwatch/archive/refs/tags/${{ version }}.tar.gz
  sha256: df5edf3e8cd8ec3ce0cf59ee48590d2f0ccad1ed6fb68ce16caf31a21983160a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - hwatch --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern alternative to the watch command
  homepage: https://github.com/blacknon/hwatch
  repository: https://github.com/blacknon/hwatch

extra:
  recipe-maintainers:
    - danielnachun
